### ISSUE TITLE
include structure

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/free-pdk-examples#7]
I think the includes should be structured in a way where they clearly separate system wide includes and local ones.

Right now there are some files like "millis.h" that are in the include root directory and are included with include "". If these are to be used system wide, I would suggest to put them into pdk/ or pdk/util. Otherwise they should reside within the example code directory.

**Comment by cpldcpu** [comment]
Also, <> should be used for system wide includes and "" for local ones. 

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf#page=182

**Comment by serisman** [comment]
I'll have to think about this a bit more.

I don't think they should go into pdk/ repo because they are more of a minimal framework than device definitions, and we aren't suggesting that they get included into SDCC.

Also, they need to be refactored so there isn't 'code' in .h files.  This probably means a lib/ folder with some changes to the Makefiles in order to compile and link each independent method as their own .a (lib) files.  This will allow SDCC to only include methods when they are actually used.  Currently there is an issue where SDCC will include the methods within the .h files multiple times (once per .c file that references a .h file).
